# @package _global_
# Training configuration with headless mode for fast training

defaults:
  - config
  - _self_
  - /physics/accurate  # Accurate physics for reducing penetration

env:
  render: false
  numEnvs: 8192

training:
  maxIterations: 10000
